# Generated by Django 6.0.5 on 2026-08-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurnedAreaAnnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biome', models.CharField(db_index=True, max_length=32, verbose_name='bioma')),
                ('state_code', models.CharField(db_index=True, max_length=2, verbose_name='código da UF')),
                ('state_uf', models.CharField(max_length=2, verbose_name='sigla da UF')),
                ('area_ha', models.FloatField(verbose_name='área em hectares')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='ano')),
                ('municipality_code', models.CharField(db_index=True, max_length=7, verbose_name='código do município')),
                ('municipality_name', models.CharField(max_length=120, verbose_name='município')),
            ],
            options={
                'verbose_name': 'área queimada anual',
                'verbose_name_plural': 'áreas queimadas anuais',
                'indexes': [models.Index(fields=['year', 'biome'], name='firemap_bur_year_827a2e_idx'), models.Index(fields=['year', 'state_code'], name='firemap_bur_year_922a13_idx'), models.Index(fields=['year', 'municipality_code'], name='firemap_bur_year_aa082d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BurnedAreaMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biome', models.CharField(db_index=True, max_length=32, verbose_name='bioma')),
                ('state_code', models.CharField(db_index=True, max_length=2, verbose_name='código da UF')),
                ('state_uf', models.CharField(max_length=2, verbose_name='sigla da UF')),
                ('area_ha', models.FloatField(verbose_name='área em hectares')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('cover_origin', models.CharField(max_length=32, verbose_name='origem da cobertura')),
                ('cover_class', models.CharField(max_length=64, verbose_name='classe de cobertura')),
                ('cover_detail', models.CharField(max_length=64, verbose_name='detalhe da cobertura')),
            ],
            options={
                'verbose_name': 'área queimada mensal',
                'verbose_name_plural': 'áreas queimadas mensais',
                'indexes': [models.Index(fields=['year', 'biome'], name='firemap_bur_year_7971ea_idx'), models.Index(fields=['year', 'state_code'], name='firemap_bur_year_d45cdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='FireRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biome', models.CharField(db_index=True, max_length=32, verbose_name='bioma')),
                ('state_code', models.CharField(db_index=True, max_length=2, verbose_name='código da UF')),
                ('state_uf', models.CharField(max_length=2, verbose_name='sigla da UF')),
                ('area_ha', models.FloatField(verbose_name='área em hectares')),
                ('season', models.PositiveSmallIntegerField(db_index=True, verbose_name='temporada')),
                ('municipality_code', models.CharField(db_index=True, max_length=7, verbose_name='código do município')),
                ('municipality_name', models.CharField(max_length=120, verbose_name='município')),
                ('tenure', models.CharField(max_length=64, verbose_name='categoria fundiária')),
                ('jurisdiction', models.CharField(max_length=32, verbose_name='jurisdição')),
                ('risk_class', models.CharField(max_length=8, verbose_name='classe de risco')),
            ],
            options={
                'verbose_name': 'risco de fogo',
                'verbose_name_plural': 'riscos de fogo',
                'indexes': [models.Index(fields=['season', 'biome'], name='firemap_fir_season_9999fc_idx'), models.Index(fields=['season', 'state_code'], name='firemap_fir_season_4a9968_idx'), models.Index(fields=['season', 'municipality_code'], name='firemap_fir_season_bd1b66_idx')],
            },
        ),
    ]
