# Generated by Django 6.0.5 on 2026-08-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'bioma',
                'verbose_name_plural': 'biomas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'área de atuação',
                'verbose_name_plural': 'áreas de atuação',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('photo', models.ImageField(blank=True, upload_to='researchers/photos/', verbose_name='foto')),
                ('consent_public', models.BooleanField(default=False, help_text="Respondeu 'Sim' à autorização de divulgar nome, e-mail e instituição para a rede.", verbose_name='autoriza divulgação')),
                ('status', models.CharField(choices=[('pending', 'Aguardando aprovação'), ('approved', 'Aprovado'), ('rejected', 'Recusado')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('form', 'Formulário de mapeamento'), ('self', 'Cadastro pelo próprio pesquisador')], default='self', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Carimbo de data/hora da resposta original.', null=True)),
                ('institution', models.CharField(blank=True, max_length=400, verbose_name='instituição')),
                ('sector', models.CharField(blank=True, choices=[('public', 'Setor público'), ('private', 'Setor privado'), ('third', 'Terceiro setor'), ('international', 'Organismo internacional'), ('other', 'Outro')], max_length=20, verbose_name='setor')),
                ('position', models.CharField(blank=True, max_length=300, verbose_name='cargo')),
                ('education_level', models.CharField(blank=True, choices=[('basic', 'Ensino básico completo'), ('undergrad_ongoing', 'Ensino superior incompleto'), ('undergrad', 'Ensino superior completo'), ('masters_ongoing', 'Mestrado em andamento'), ('masters', 'Mestrado'), ('phd_ongoing', 'Doutorado em andamento'), ('phd', 'Doutorado')], max_length=30, verbose_name='formação')),
                ('country', models.CharField(blank=True, default='Brasil', max_length=80, verbose_name='país')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='município')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('main_research_area', models.CharField(blank=True, max_length=400, verbose_name='principal área de pesquisa')),
                ('fire_focused', models.BooleanField(blank=True, null=True, verbose_name='pesquisa majoritariamente focada no fogo')),
                ('years_researching', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='anos pesquisando fogo')),
                ('years_researching_raw', models.CharField(blank=True, help_text='Resposta original, sem tratamento.', max_length=120)),
                ('focused_on_brazil', models.BooleanField(blank=True, null=True, verbose_name='pesquisa focada no Brasil')),
                ('other_territories', models.CharField(blank=True, max_length=400, verbose_name='outros territórios')),
                ('research_description', models.TextField(blank=True, verbose_name='descrição da pesquisa')),
                ('develops_technology', models.BooleanField(blank=True, null=True, verbose_name='desenvolve tecnologias')),
                ('technology_description', models.TextField(blank=True, verbose_name='tecnologias desenvolvidas')),
                ('involves_communities', models.BooleanField(blank=True, null=True, verbose_name='envolve comunidades humanas')),
                ('social_description', models.TextField(blank=True, verbose_name='pesquisa socioambiental e econômica')),
                ('works_with_education', models.BooleanField(blank=True, null=True, verbose_name='atua em educação ambiental')),
                ('education_description', models.TextField(blank=True, verbose_name='pesquisa em educação ambiental')),
                ('governance_description', models.TextField(blank=True, verbose_name='pesquisa em governança e políticas públicas')),
                ('publications', models.TextField(blank=True, verbose_name='principais produções')),
                ('funding_sources', models.CharField(blank=True, max_length=500, verbose_name='fontes de financiamento')),
                ('partnerships', models.TextField(blank=True, verbose_name='parcerias nacionais')),
                ('foreign_partnerships', models.TextField(blank=True, verbose_name='parcerias estrangeiras')),
                ('outreach', models.CharField(blank=True, max_length=500, verbose_name='divulgação para público não acadêmico')),
                ('lattes_url', models.CharField(blank=True, max_length=500, verbose_name='currículo Lattes')),
                ('orcid_url', models.CharField(blank=True, max_length=200, verbose_name='ORCID')),
                ('linkedin_url', models.CharField(blank=True, max_length=300, verbose_name='LinkedIn')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='telefone')),
                ('gender', models.CharField(blank=True, max_length=60, verbose_name='gênero')),
                ('race', models.CharField(blank=True, max_length=60, verbose_name='raça/cor')),
                ('age_range', models.CharField(blank=True, max_length=40, verbose_name='faixa etária')),
                ('has_children', models.BooleanField(blank=True, null=True, verbose_name='tem filhos')),
                ('origin_country', models.CharField(blank=True, max_length=80, verbose_name='país de origem')),
                ('origin_state', models.CharField(blank=True, max_length=80, verbose_name='estado de origem')),
                ('biomes', models.ManyToManyField(blank=True, related_name='researchers', to='researchers.biome', verbose_name='biomas')),
                ('research_areas', models.ManyToManyField(blank=True, related_name='researchers', to='researchers.researcharea', verbose_name='áreas de atuação')),
                ('user', models.OneToOneField(blank=True, help_text='Conta que pode editar este perfil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pesquisador',
                'verbose_name_plural': 'pesquisadores',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['status', 'consent_public'], name='researchers_status_6930fc_idx'), models.Index(fields=['state'], name='researchers_state_93f626_idx')],
            },
        ),
    ]
