# Generated by Django 6.0.5 on 2026-08-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        # renomeia em vez de remover+criar: assim as coordenadas já importadas
        # (270 pesquisadores) não se perdem
        migrations.RenameField(
            model_name='researcher',
            old_name='latitude',
            new_name='institution_latitude',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='longitude',
            new_name='institution_longitude',
        ),
        migrations.AddField(
            model_name='researcher',
            name='residence_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade onde mora'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='residence_country',
            field=models.CharField(blank=True, default='Brasil', max_length=80, verbose_name='país onde mora'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='residence_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='residence_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='residence_state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF onde mora'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='município da instituição'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=80, verbose_name='país da instituição'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF da instituição'),
        ),
    ]
